Hostname "r2s"
Interval 60
LoadPlugin cpu
LoadPlugin memory
LoadPlugin df
LoadPlugin disk
LoadPlugin interface
LoadPlugin conntrack
LoadPlugin processes
LoadPlugin uptime
LoadPlugin thermal
LoadPlugin rrdtool
<Plugin df>
  MountPoint "/"
  IgnoreSelected false
</Plugin>
<Plugin processes>
  Process "dnsmasq"
  Process "dockerd"
</Plugin>
<Plugin rrdtool>
  DataDir "/data/metrics/rrd"
  CacheTimeout 120
  CacheFlush 900
  RRARows 240
  RRATimespan 86400
  RRATimespan 604800
  RRATimespan 2678400
</Plugin>
